# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1da2b36f4a52e62854645db8cf06a965"
name = "u-torch-app"
handle = "u-torch-app"
application_url = "https://minimal-sean-desired-brazil.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "torch-shop-test-01.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://minimal-sean-desired-brazil.trycloudflare.com/auth/callback",
  "https://minimal-sean-desired-brazil.trycloudflare.com/auth/shopify/callback",
  "https://minimal-sean-desired-brazil.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
